const nome = 'Luiz'

function falaNome(){
    console.log(nome);
}

falaNome();

/*

FUNCIONA ASSIM: CASO DENTRO DA FUNCÃO "FALANOME()" EU TENHA UMA CONST/LET CUJO O NOME TAMBÉM SEJA "NOME" ELE IRÁ PEGAR O VALOR QUE TEM DENTRO DELA. EX = 'CARLOS', PORÉM CASO NÃO TENHA A VARIÁVEL DENTRO DA MINHA FUNÇÃO, ELE IRÁ VERIFICAR SE ENCONTRA ESSA VARIÁVEL COM ESSE MESMO "NOME" E CASO ENCONTRAR, IRÁ TRAZER O VALOR DELA, CASO NÃO ENCONTRAR, IRÁ DAR ERRO.

*/

